[package]
name = "post"
version = "0.1.0"
edition = "2021"

[dependencies]
bellperson = { path = "../bellperson" }
rand = "0.8"
fff = { path = "../ff", features = ["derive"] }
openssl = { version = "0.10.38" }
rayon = "1.5"
